trigger: none
pool: agent-pool

steps:
- task: TerraformInstaller@1
  displayName: terraform install
  inputs:
    terraformVersion: 'latest'

- task: TerraformTask@5
  displayName: terraform init
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/pipline-practice'
    backendServiceArm: 'terraform-service-connection'
    backendAzureRmResourceGroupName: 'rg-pipeline'
    backendAzureRmStorageAccountName: 'stgpipe'
    backendAzureRmContainerName: 'container-pipe'
    backendAzureRmKey: 'sandhya.tfstate'

- task: TerraformTask@5
  displayName: terraform plan
  inputs:
    provider: 'azurerm'
    command: 'plan'
    workingDirectory: '$(System.DefaultWorkingDirectory)/pipline-practice'
    environmentServiceNameAzureRM: 'terraform-service-connection'

- task: TerraformTask@5
  displayName: terraform apply
  inputs:
    provider: 'azurerm'
    command: 'apply'
    workingDirectory: '$(System.DefaultWorkingDirectory)/pipline-practice'
    commandOptions: '-auto-approve'
    environmentServiceNameAzureRM: 'terraform-service-connection'
